sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - iojs
before_install:
  - npm i -g npm@^2.0.0
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - npm prune
script:
  - npm run test
after_success:
  - npm run semantic-release
